// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TBE.PricingService.Infrastructure;

#nullable disable

namespace TBE.PricingService.Infrastructure.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    partial class PricingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                b.Property<DateTimeOffset?>("Consumed").HasColumnType("datetimeoffset");
                b.Property<DateTime>("Created").HasColumnType("datetime2");
                b.Property<DateTime?>("Delivered").HasColumnType("datetime2");
                b.Property<string>("ConsumerId").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<Guid>("MessageId").HasColumnType("uniqueidentifier");
                b.Property<int>("ReceiveCount").HasColumnType("int");
                b.Property<DateTime?>("ExpirationTime").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasAlternateKey("MessageId", "ConsumerId");
                b.ToTable("InboxState");
            });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
            {
                b.Property<long>("SequenceNumber")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));
                b.Property<string>("Body").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("ContentType").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<Guid?>("ConversationId").HasColumnType("uniqueidentifier");
                b.Property<Guid?>("CorrelationId").HasColumnType("uniqueidentifier");
                b.Property<DateTime?>("Delivered").HasColumnType("datetime2");
                b.Property<string>("DestinationAddress").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<DateTime?>("EnqueueTime").HasColumnType("datetime2");
                b.Property<DateTime>("ExpirationTime").HasColumnType("datetime2");
                b.Property<string>("FaultAddress").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<Guid?>("InboxMessageId").HasColumnType("uniqueidentifier");
                b.Property<string>("InboxConsumerId").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<Guid>("MessageId").HasColumnType("uniqueidentifier");
                b.Property<string>("MessageType").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<Guid?>("OutboxId").HasColumnType("uniqueidentifier");
                b.Property<string>("ResponseAddress").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<DateTime>("SentTime").HasColumnType("datetime2");
                b.HasKey("SequenceNumber");
                b.ToTable("OutboxMessage");
            });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
            {
                b.Property<Guid>("OutboxId").HasColumnType("uniqueidentifier");
                b.Property<DateTime>("Created").HasColumnType("datetime2");
                b.Property<DateTime?>("Delivered").HasColumnType("datetime2");
                b.Property<long?>("LastSequenceNumber").HasColumnType("bigint");
                b.Property<int>("Version").IsConcurrencyToken().HasColumnType("int");
                b.HasKey("OutboxId");
                b.ToTable("OutboxState");
            });

            modelBuilder.Entity("TBE.PricingService.Application.Rules.Models.MarkupRule", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<string>("ProductType").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string?>("AirlineCode").HasMaxLength(3).HasColumnType("nvarchar(3)");
                b.Property<string?>("RouteOrigin").HasMaxLength(3).HasColumnType("nvarchar(3)");
                b.Property<int>("Type").HasColumnType("int");
                b.Property<decimal>("Value").HasColumnType("decimal(18,4)");
                b.Property<decimal?>("MaxAmount").HasColumnType("decimal(18,4)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Channel").IsRequired().HasMaxLength(5).HasColumnType("nvarchar(5)");
                b.HasKey("Id");
                b.HasIndex("ProductType", "Channel", "IsActive").HasDatabaseName("IX_MarkupRules_ProductType_Channel_IsActive");
                b.ToTable("MarkupRules");
            });

            // Plan 05-02 Task 1 — D-36 per-agency markup rules.
            modelBuilder.Entity("TBE.PricingService.Application.Agency.AgencyMarkupRule", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<Guid>("AgencyId").HasColumnType("uniqueidentifier");
                b.Property<string?>("RouteClass").HasMaxLength(32).HasColumnType("nvarchar(32)");
                b.Property<decimal>("FlatAmount").HasColumnType("decimal(18,4)");
                b.Property<decimal>("PercentOfNet").HasColumnType("decimal(5,4)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("AgencyId", "RouteClass")
                    .IsUnique()
                    .HasDatabaseName("IX_AgencyMarkupRules_Active")
                    .HasFilter("[IsActive] = 1");
                b.ToTable("AgencyMarkupRules", "pricing");
            });
#pragma warning restore 612, 618
        }
    }
}
